### ISSUE TITLE
TOML configuration file instead of absolte paths: code clean up

### ISSUE THREAD

**Issue by xaratustrah** [DFreireF/TDMSchopper#5]
Code on GitHUB should not contain any absolute path and names from local directories. Currently there are many such entries, e.g. this one:
https://github.com/DFreireF/tdmchops/blob/dcd096fb30b7a941e7a018e333964ae915a3d7c3/tdmchops/model.py#L248

The code needs clean up. Instead one can use a TOML configuration file, like `pathsettings.toml` that reads all such fixed parameters:

```toml
# this is a config file
input_filepath = ""
output_filepath = ""
```
the empty version goes on GitHUB, a modified version `pathsettings_myown.toml` is kept locally, and used with the script using the `argparse`.

```
tdmchops --pathsettings pathsettings_my.toml
```

**Comment by DFreireF** [comment]
Fixed. Although now is also in this issue :D.
